### ISSUE TITLE
Add a human readable output for bootc status

### ISSUE THREAD

**Issue by mrguitar** [containers/bootc#408]
Coming from rpm-ostree, I can quickly see & more importantly grok the output from` rpm-ostree status`. `bootc status` has all the good stuff, but it takes much longer to wade through the output, and scroll up in the terminal, etc. Adding an option to boil it down like `--pretty` or `--human`, as Colin suggested, would really help speed me up and add better clarity for users. I can definitely see a kube admin preferring the existing output, so let's not lose that.

**Comment by cgwalters** [comment]
Yes totally!  To give more color to this the current bootc design is very much influenced by the "imperative + DBus API" of rpm-ostree being tough to deal with for systems like the https://github.com/openshift/machine-config-operator/ that want to actually manage the system declaratively in a Kube-like style.  IOW we want to support agents scripting, in the general case.

However we should *totally* have nice ergonomics for standalone agentless systems, and this is very much part of that.  Labeling as good-first-issue.

**Comment by lukewarmtemp** [comment]
This is the current output for `bootc status`:
```
sudo ./bootc status
apiVersion: org.containers.bootc/v1alpha1
kind: BootcHost
metadata:
  name: host
spec:
  image:
    image: localhost:5000/fcos:latest
    transport: registry
  bootOrder: default
status:
  staged: null
  booted:
    image:
      image:
        image: localhost:5000/fcos:latest
        transport: registry
      version: 40.20240504.3.0
      timestamp: null
      imageDigest: sha256:2f7207cddc3b01ee0980a4c8152d1277e0a0b5fe0ebff27bcc5e9b101e08d7ce
    cachedUpdate: null
    incompatible: false
    pinned: false
    ostree:
      checksum: 05b704430628019881d929c204ad4293230dc34d7df962428268faf145be8ac7
      deploySerial: 0
  rollback:
    image:
      image:
        image: quay.io/luyang/fcos-karg-test2
        transport: registry
      version: 40.20240504.3.0
      timestamp: null
      imageDigest: sha256:d5d43c888d3017c19ee912714ce206716dd56564eea5818e5b2f32f6e74feae5
    cachedUpdate: null
    incompatible: false
    pinned: false
    ostree:
      checksum: 6f3d22c95edbd7257e5de1a6dcd88e31c4536031776230e4daa1629f679cc098
      deploySerial: 0
  rollbackQueued: false
  type: bootcHost
```
What information is most important to keep when making the human readable option?
