### ISSUE TITLE
bootc switch does not tell me when it ignores my /etc changes

### ISSUE THREAD

**Issue by stefwalter** [containers/bootc#438]
I've made changes to /etc in my Container file:

Tag ```quay.io/swalter/monday:test1```
```
RUN echo 'test1' > /etc/blah
```

Tag ```quay.io/swalter/monday:test2```

```
RUN echo 'test2' > /etc/blah
```

If I modify /etc/blah, and then run ```bootc switch``` the system ignores the changes represented in my Containerfile, but doesn't tell me about this. This doesn't represent typical behavior I expect from a container. I expect the changes in ```/etc``` to take effect, or at a minimum for ```bootc``` to tell me when this isn't the case:

```
# cat /etc/blah 
test2
# bootc status | grep image
  image:
    image: quay.io/swalter/monday:test2
    image:
      image:
        image: quay.io/swalter/monday:test2
      imageDigest: sha256:f1ec8375caf4ec43d5dd37f26dcfcca8eb7279dbee1a368f55b394e551096112
# echo "test different" >> /etc/blah
# bootc switch quay.io/swalter/monday:test1
No changes in quay.io/swalter/monday:test1 => sha256:09f60a3d90f9604c5802eca575e56df262b55f78f4cd20269c0aaae81c870ce7
Queued for next boot: ostree-unverified-registry:quay.io/swalter/monday:test1
  Version: stream9.20240319.0
  Digest: sha256:09f60a3d90f9604c5802eca575e56df262b55f78f4cd20269c0aaae81c870ce7
# reboot 
...
# cat /etc/blah 
test2
test different
```
