### ISSUE TITLE
Pinning functionality

### ISSUE THREAD

**Issue by tulilirockz** [containers/bootc#904]
It would be interesting to have something like the `ostree admin pin (number)` functionality on bootc directly. Like, sometimes we get some users that have a functioning system on one deployment but for whatever reason the other one doesnt work on their system, that would make it so the user can have that safety that they're never going to have their system "bricked"

**Comment by p5** [comment]
Took a quick look at the readonly implementation of pinning, and it looks quite straight forward.  Bootc does receive information about these pinned deployments, though discards them shortly after.  

There will need to be some design decisions taken as to how this will be exposed to the user (i.e. the human and machine readable formats).

Below is an example of a YAML output, treating the pinned deployments as a Vec<>, and letting serde do the deserialization.  

```
❯ sudo ./target/debug/bootc status --format yaml
apiVersion: org.containers.bootc/v1
kind: BootcHost
metadata:
  name: host
spec:
  image:
    image: ghcr.io/rsturla/eternal-linux/lumina:42-nvidia-open
    transport: registry
    signature: containerPolicy
  bootOrder: default
status:
  staged: null
  booted:
    image:
      image:
        image: ghcr.io/rsturla/eternal-linux/lumina:42-nvidia-open
        transport: registry
        signature: containerPolicy
      version: '250403'
      timestamp: 2025-04-03T01:44:51Z
      imageDigest: sha256:e53063e967e52c07d7fffd1714fb3d5ff3f97675608ca007419ba1a68d2ba35f
    cachedUpdate: null
    incompatible: false
    pinned: false
    store: ostreeContainer
    ostree:
      checksum: fe3eb280f463608dbf3f40f57e9898f47252e42dde378dd48e28bc63c713e334
      deploySerial: 0
    deploymentUnlockedState: null
  rollback:
    image:
      image:
        image: ghcr.io/rsturla/eternal-linux/lumina:42-nvidia-open
        transport: registry
        signature: containerPolicy
      version: '250401'
      timestamp: 2025-04-01T21:48:54Z
      imageDigest: sha256:438654e56f50129441905df1fa72f026478aff6e3850d77ec8c8dda3e5f91ebe
    cachedUpdate:
      image:
        image: ghcr.io/rsturla/eternal-linux/lumina:42-nvidia-open
        transport: registry
        signature: containerPolicy
      version: '250403'
      timestamp: 2025-04-03T01:44:51Z
      imageDigest: sha256:e53063e967e52c07d7fffd1714fb3d5ff3f97675608ca007419ba1a68d2ba35f
    incompatible: false
    pinned: false
    store: ostreeContainer
    ostree:
      checksum: 6b28207754d2e6cd5b5bdf6756c5c46e06879af2c1e791d0ac58fa8a8f480e23
      deploySerial: 0
    deploymentUnlockedState: null
  pinned:
  - image:
      image:
        image: ghcr.io/rsturla/eternal-linux/lumina:stable-nvidia-open
        transport: registry
        signature: containerPolicy
      version: '250329'
      timestamp: 2025-03-29T01:44:28Z
      imageDigest: sha256:79403bb8be5515a7937710310a68020724c25488ba687269832189e6375da227
    cachedUpdate:
      image:
        image: ghcr.io/rsturla/eternal-linux/lumina:stable-nvidia-open
        transport: registry
        signature: containerPolicy
      version: '250401'
      timestamp: 2025-04-01T02:11:10Z
      imageDigest: sha256:1d7d40408ca6eda7a355162c7a89646d0f99b17b426eb95323fa6bd1ab4ebb85
    incompatible: false
    pinned: true
    store: ostreeContainer
    ostree:
      checksum: 99b2cc3b6edce9ebaef6a6076effa5ee3e1dcff3523016ffc94a1b27c6c67e12
      deploySerial: 0
    deploymentUnlockedState: null
  rollbackQueued: false
  type: bootcHost
```
